### ISSUE TITLE
Priority List

### ISSUE THREAD

**Issue by CosmicWebServices** [TheMonsterFromTheDeep/pyfancy#11]
This is everything that I have seen we have been doing or want to do. Tell me if I missed one
- [ ] Parsing
- [ ] Add more colors?
- [ ] Talk about syntax
- [ ] Debug
- [ ] Find and fix bugs

**Comment by joker314** [comment]
Why did you merge mine?

**Comment by joker314** [comment]
It wasn't done. Anyway, I'll just make another one, I found all bugs and got it to work

**Comment by CosmicWebServices** [comment]
It was by accident and I reverted the merge

**Comment by joker314** [comment]
Don't worry, after I spent all that time... @TheMonsterFromTheDeep  did exactly what I was about to do! And I spent so much effort! Thanks @TheMonsterFromTheDeep  nice job finding it before I did :) :+1:

**Comment by CosmicWebServices** [comment]
:) How do you like the list anything to add or remove

**Comment by joker314** [comment]
Correct typos

**Comment by joker314** [comment]
in your list, there are typos like "syntex"

**Comment by CosmicWebServices** [comment]
Fixed

**Comment by joker314** [comment]
Ok, let's talk about syntax right now!

**Comment by joker314** [comment]
I'm going to add to the docs

**Comment by CosmicWebServices** [comment]
Go to #8 to talk about it
