### ISSUE TITLE
Some more function ideas

### ISSUE THREAD

**Issue by joker314** [TheMonsterFromTheDeep/pyfancy#14]
We should implement a "strip" function to _return_ a string that has no colour style in it

Any other suggestions?

**Comment by CosmicWebServices** [comment]
We have raw for that...

**Comment by TheMonsterFromTheDeep** [comment]
So wait, do you mean something like this?

``` python
pyfancy().red("Something ").blue("something else").strip() # Returns "Something something else"
```

Or do you mean something like this:

``` python
text = pyfancy().red("this is some scary text").get()
textStripped = pyfancy().strip(text)
```

**Comment by joker314** [comment]
Both would work, because the passed text works as normal, appending to the object. However, I would expect it to be used like so:

``` python
import re
text = pyfancy().rainbow("Hi, how are you?")
text.output()
for i in text.strip():
    #Some code to process the text, maybe some regexes
```

**Comment by TheMonsterFromTheDeep** [comment]
Oh right! I forgot that it was possible to get a pyfancy object from a pyfancy call. :package:

**Comment by joker314** [comment]
@CosmicWebServices It isn't appending to the object, it is stripping previous colour styles from it.

**Comment by joker314** [comment]
@TheMonsterFromTheDeep Yep. And implementation should just be testing the`ord()` range or something of each letter

**Comment by joker314** [comment]
Also, does this work: `pyfancy(pyfancy())` to clone an existing pyfancy object? Also, does this work `pyfancy(pyfancy().get())` ?

**Comment by TheMonsterFromTheDeep** [comment]
There are no constructors with arguments yet. I think that's the `__init__` method? (Sorry, Python noob here :P)

But yeah, that would be a good idea. Cloning objects can be useful.

I'm not sure, then, where this leaves me with my regex matching thing though - because I'm not sure we would want those rules to persist across pyfancy objects. Maybe we should come up with a better syntax? :/

**Comment by joker314** [comment]
Yeah.

gotta go, be back in ~ 2 hours

**Comment by TheMonsterFromTheDeep** [comment]
I'm gonna be leaving for vacation in an hour or something :P

**Comment by joker314** [comment]
Ok

**Comment by CosmicWebServices** [comment]
Moved issue.
