### ISSUE TITLE
Change run() to parse(); Discuss syntax

### ISSUE THREAD

**Issue by TheMonsterFromTheDeep** [TheMonsterFromTheDeep/pyfancy#8]
I think that parse() would be a better name for the parser module, as I think it sounds more natural...

Compare:

``` python
pyfancy().run("RED{something} GREEN{something}").output()
```

``` python
pyfancy().parse("RED{something} GREEN{something}").output()
```

It isn't really _running_ anything, it's just parsing something.

As it is, though, I feel like we need to establish the parsing language more clearly - right now it doesn't really feel natural. I think it should also support really advanced constructs, like maybe it can have optional arguments for regex matching to specific colors?

**Comment by CosmicWebServices** [comment]
I agree with `.parse()` And I agree with ur statement

**Comment by TheMonsterFromTheDeep** [comment]
If we can all agree on parse() (or on a different name...) then we should start discussing parser syntax

**Comment by CosmicWebServices** [comment]
@joker314 How do you feel about this?

**Comment by CosmicWebServices** [comment]
@TheMonsterFromTheDeep Slightly off-topic but who is now on out team I know you, joker, me anyone else?

**Comment by TheMonsterFromTheDeep** [comment]
I don't know, I know Jonathan50 helped but he might have just wanted to help with that one thing

Us three are the only guys active on this right now.

**Comment by joker314** [comment]
I am fine with it, and here is some fun syntax we could use
`pyfancyObject.regex().match(str)`
or
`pyfancyObject.match(str)`
but in the end, will we be using the re module?
`import re`
as for parsing syntax, I was currently basing it on @**init**'s idea

`.parse("funcName { the string and you can escape like so \{ hi \} and you can nest bold {some text} }")`

What would y'all prefer

**Comment by TheMonsterFromTheDeep** [comment]
I sort of like braces, but I sort of (?) like something like `{text:red}` better, but then again, that's not as good because it has less clear syntax and more reserved characters...

This, I guess, is why language design is hard. :]

**Comment by joker314** [comment]
We could go all HTML
`<red>Lolololool</red>`

**Comment by joker314** [comment]
Or
`{text red}`
therefore the final space dliminates

**Comment by joker314** [comment]
Or BBCode equivalent of the HTML.
Any input?

**Comment by CosmicWebServices** [comment]
I want to make this as simple for the user as possible... Though this will only for PRO Pyfancy users if I understand correctly

**Comment by CosmicWebServices** [comment]
@joker314 I like your idea though it is not that practical

**Comment by joker314** [comment]
Which one? and yeah, it is meant to be for pros. I have an idea: parse accepts more than 1 arg, give me a sec 4 research

**Comment by CosmicWebServices** [comment]
The bbcode/html one

**Comment by joker314** [comment]
Ok. I'm now thinking of string formatting like so:
- parse accepts a string arg followed by variable amount of args ([link](http://stackoverflow.com/questions/919680/can-a-variable-number-of-arguments-be-passed-to-a-function))
- you would do:
  `obj.parse("Hi {lol this is \{all\} red} and {green and ALSO {bold} u know } stuff", "red", "green", "bold")`

**Comment by CosmicWebServices** [comment]
confused

**Comment by CosmicWebServices** [comment]
what would be the output so I understand

**Comment by joker314** [comment]
that was equal to
`obj.raw("Hi").red("lol this is {all} red").raw(" and ").green("green and ALSO ").bold("bold").raw().red("u know").raw(" stuff")`

but notice the inconvenient empty raw to close the bold but not the red. That is why this would be beneficial

**Comment by CosmicWebServices** [comment]
OK now I get it

**Comment by joker314** [comment]
So the lit of optional args will be the styles of the opening braces from left to right

**Comment by joker314** [comment]
*lidt

**Comment by joker314** [comment]
*list

**Comment by TheMonsterFromTheDeep** [comment]
I think I have come up with a syntax that could work pretty well....

Basically, there could be two methods, parse() and match(), which apply color to the _already existing text_ using either our parser rules or regex rules.

match() would apply regex rules that were previously defined, using another new method, rule(), which would take a regex and then the styles that would be applied to it.

The format for parse() would just be `{styles text}`, where styles is a comma-separated list of names (and numbers?) where invalid names would be ignored. So, `{red Hello} {blue,bold World}` would print Hello in red and World in bold blue. (We might also need a special syntax for things like rainbow, maybe something like an asterisk or something? I guess we wouldn't really need one, but things like rainbow are basically one-off (although bold and stuff could still work) so I guess we'll have to discuss that)

Basically, then, it would be possible to do this:

``` python
pyfancy().raw("And so the programmer encountered... {red,bold PHP!}").parse().output()
```

And then maybe for conciseness that text could be provided directly in the pyfancy() call:

``` python
pyfancy("And so the programmer encountered... {red,bold PHP!}").parse().output()
```

Or in the parse statement:

``` python
pyfancy().parse("And so the programmer encountered... {red,bold PHP!}").output()
```

And then maybe for even more conciseness it would be possible to just call that directly from pyfancy() using some other parameter? I guess we can discuss that.

Then regexes could also be done pretty simply:

``` python
pyfancy("The time epoch is January 1, 1970").rule("[0-9]+","underline").match().output() # Numbers are underlined
```

I don't know. What do you guys think?

**Comment by TheMonsterFromTheDeep** [comment]
Actually, the parse() and match() statements should probably only operate on the text passed to them, so that other text can be left alone.

Also, what escape character do we want to use? We could use \, but that's already an escape character, so it would have to be input as \.

**Comment by CosmicWebServices** [comment]
Question what if the person wants to say red or bold in the sentence would it not get confused?

**Comment by CosmicWebServices** [comment]
I like the second and the last one

**Comment by joker314** [comment]
I don't think parse should be called emptily, because we currently can't differentiate between all calls made previously. I suggest:
`pyfancy("Starting text or other pyfancy object").parse("And so the programmer encountered... {red,bold PHP!}").output()`

or

`pyfancy("The time epoch is January 1, 1970").match("[0-9]+","underline").output()`

or my way would be

`pyfancy("Starting text or other pyfancy object").parse("And so the programmer encountered... {{ PHP!}}", "red", "bold").output()`

**Comment by joker314** [comment]
Shall I go implement it, and if so, which one?

**Comment by CosmicWebServices** [comment]
Lets wait for @TheMonsterFromTheDeep input

**Comment by joker314** [comment]
for the regex, won't it require the

``` python
import re
```

?

**Comment by joker314** [comment]
@mention @TheMonsterFromTheDeep

**Comment by TheMonsterFromTheDeep** [comment]
Yeah guys sorry I was at work :package: 

But anyways I think ya'll might have misunderstood what I was saying (at least in my corrected post). Maybe not...

Basically, parse() would parse whatever text was in it. I think that the best syntax would be `{modifiers text}` because it is simple and also really clear.

I think for regex matching there are two options: one, we use the rule() syntax to create rules that match() then matches, or two, we list the rules as extra arguments of match():

``` python
pyfancy().match("The time epoch is January 1, 1970","[0-9]+","underlined").output()
```

But this is more susceptible to error on the part of the programmer. Using rule() would allow for the definition of arbitrary rules and then match() would match its argument to those rules using regexes.

Of course, the only limit there is that the rules are persistent until the pyfancy call is finished, but maybe that could be fixed with a clearrules() or something?

``` python
pyfancy().rule("[0-9]+","underlined").match("The time epoch is January 1, 1970","[0-9]+").clearrules().rule("[0-9]+","bold,red").match("The current year is 2016").output()
```

I don't know. I guess it's up to you all to decide what the syntax for regular expression is.

Keep in mind that regular expression matching is _completely_ separate from the parse() command.

Also, @joker314 , why do you believe that providing the styles separately would be better? I feel that the syntax I came up with is nice because it is clean and very clear. Having the styles provided separately would make it much harder to read and modify.

The first priority, is, of course, the end user, so if you guys think we can come up with an even better syntax I am of course open to suggestions. I just think we should do something that is simple, clean, and clear.

**Comment by joker314** [comment]
Yeah, OK. So the user must type all modifiers without spaces seperated by comas? Sure. I can work on that later, unless any of you want to start before I get a chance

**Comment by TheMonsterFromTheDeep** [comment]
No, the syntax was modifiers are separated by only commas and then there is a space before the text. This should be pretty easy to parse.

**Comment by joker314** [comment]
Yep, I don't mind implementing, so you can assign me?

**Comment by CosmicWebServices** [comment]
Done

**Comment by joker314** [comment]
escape code: `\{bla,bla text\}`
right?

**Comment by joker314** [comment]
Also, I will allow the user to nest? 
`{red hi {bold I'm bold and red} but I'm only red}`

**Comment by TheMonsterFromTheDeep** [comment]
Sure! Why not?

**Comment by joker314** [comment]
kk

**Comment by joker314** [comment]
Forget it, I don't have enough time. However, I do have some tips if any of you decide to do it: Go char by char, if you see a backslash append it to a variable as normal, but skip next char. Store what part you aer doing e.g. "command" or "text" and when you see a deimintor "{}, " then execute a function paired with text in a dict e.g. {"red":self.red, "blue":self.blue} etc.

**Comment by CosmicWebServices** [comment]
I o not have the skill to do it

**Comment by TheMonsterFromTheDeep** [comment]
I might be able to do this at somepoint.

**Comment by CosmicWebServices** [comment]
OK

**Comment by joker314** [comment]
Okay, we are going to use the syntax `{EFFECT your text goes here}`. Nesting is allowed, `{A B {C D} E}` is the same as `{A B} {C D} {A E}`

**Comment by CosmicWebServices** [comment]
@joker314 great that you want us to work on this again but can we move the issues to the current repo here https://github.com/ilovecode1/Pyfancy-2

**Comment by TheMonsterFromTheDeep** [comment]
@CosmicWebServices if you want, I can transfer ownership of this repo to you; that way it can keep all issues etc

**Comment by CosmicWebServices** [comment]
Well I already moved all the code to the new one

**Comment by CosmicWebServices** [comment]
Moved issue.

**Comment by TheMonsterFromTheDeep** [comment]
@CosmicWebServices in that case can I have access to your repo?

**Comment by CosmicWebServices** [comment]
Sure :D

**Comment by jeandrek** [comment]
:o:h
